name: CI

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches: [ master]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
    
    name: Test @ ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: ./
        with: 
          release: 8.3.0.202004 
      
      - run: rx-elf-gcc -v
